### ISSUE TITLE
Ask: backward compatibility

### ISSUE THREAD

**Issue by habibillah** [goetas/xsd-reader#12]
I see this repo have been abandoned and moved to https://github.com/goetas-webservices/xsd-reader. Is that new repo has same code base and backward compatibility with this repo? same question for `goetas/xsd2php`

**Comment by goetas** [comment]
Regarding the `xsd-reader`, the new package is almost fully compatible, the only change is a different namespace.

Regarding the `xsd2php`, the new package is generally compatible, main changes are: 
- different namespace
- different command line parameters
- added yaml configuration file

Beside this, the generated php files and yaml metadata, are fully compatible with the old package.

**Comment by habibillah** [comment]
Thank you for your quick response :+1:
